#!/bin/bash

if [ "$1" = "" ]
  then
    HOME_DIR="${HOME}"
  else
    HOME_DIR="/home/${1}" # assumes linux
fi

echo "Creating dotfile symlinks using home directory: ${HOME_DIR}"

if [ "$1" != "core" ]
  then
    ln -sfn ${HOME_DIR}/.dotfiles/vim ${HOME_DIR}/.vim
    ln -sf ${HOME_DIR}/.dotfiles/vimrc ${HOME_DIR}/.vimrc
fi
ln -sf ${HOME_DIR}/.dotfiles/bash_aliases ${HOME_DIR}/.bash_aliases
ln -sf ${HOME_DIR}/.dotfiles/gitconfig ${HOME_DIR}/.gitconfig
ln -sf ${HOME_DIR}/.dotfiles/gitignore_global ${HOME_DIR}/.gitignore_global
ln -sf ${HOME_DIR}/.dotfiles/bash_prompt ${HOME_DIR}/.bash_prompt
ln -sf ${HOME_DIR}/.dotfiles/inputrc ${HOME_DIR}/.inputrc
ln -sf ${HOME_DIR}/.dotfiles/bash_env ${HOME_DIR}/.bash_env
ln -sf ${HOME_DIR}/.dotfiles/rspec ${HOME_DIR}/.rspec
ln -sf ${HOME_DIR}/.dotfiles/docker_env ${HOME_DIR}/.docker_env
ln -sf ${HOME_DIR}/.dotfiles/pryrc ${HOME_DIR}/.pryrc
ln -sfn ${HOME_DIR}/.dotfiles/bash_completion.d ${HOME_DIR}/.bash_completion.d

cat ${HOME_DIR}/.bash_profile | grep "bash_env" &> /dev/null
if [ "$?" != 0 ]
  then
    printf "\nif [ -f ${HOME_DIR}/.bash_env ]; then\n  . ${HOME_DIR}/.bash_env\nfi\n" >> ${HOME_DIR}/.bash_profile
fi


cat ${HOME_DIR}/.bash_profile | grep bash_aliases &> /dev/null
if [ "$?" != 0 ]
  then
    printf "\nif [ -f ${HOME_DIR}/.bash_aliases ]; then\n  . ${HOME_DIR}/.bash_aliases\nfi\n" >> ${HOME_DIR}/.bash_profile
    if [ "$?" = 1 ] # could be readonline file system, core os for example
      then
        BASH_PROFILE_CONTENT=$(cat ${HOME_DIR}/.bash_profile)
        rm ${HOME_DIR}/.bash_profile
        printf "${BASH_PROFILE_CONTENT}\n\nif [ -f .bash_aliases ]; then\n  . ${HOME_DIR}/.bash_aliases\nfi" >> ${HOME_DIR}/.bash_profile
    fi
fi

cat ${HOME_DIR}/.bash_profile | grep "docker_env" &> /dev/null
if [ "$?" != 0 ]
  then
    printf "\nif [ -f ${HOME_DIR}/.docker_env ]; then\n  . ${HOME_DIR}/.docker_env\nfi\n" >> ${HOME_DIR}/.bash_profile
fi

cat ${HOME_DIR}/.bash_profile | grep "bash_prompt" &> /dev/null
if [ "$?" != 0 ]
  then
    printf "\nif [ -f ${HOME_DIR}/.bash_prompt ]; then\n  . ${HOME_DIR}/.bash_prompt\nfi\n" >> ${HOME_DIR}/.bash_profile
fi

cat ${HOME_DIR}/.bash_profile | grep "bash_completion\.d" &> /dev/null
if [ "$?" != 0 ]
  then
    printf "for f in ~/.bash_completion.d/* ; do source \$f; done\n" >> ${HOME_DIR}/.bash_profile
fi
