#!/bin/bash

if [ "$1" = "" ]
  then
    HOME_DIR="${HOME}"
  else
    HOME_DIR="/home/${1}" # assumes linux
fi

echo "Creating dotfile symlinks using home directory: ${HOME_DIR}"
ln -sfn ${HOME_DIR}/.dotfiles/vim ${HOME_DIR}/.vim
ln -sf ${HOME_DIR}/.dotfiles/vimrc ${HOME_DIR}/.vimrc
ln -sf ${HOME_DIR}/.dotfiles/bash_aliases ${HOME_DIR}/.bash_aliases

cat ${HOME_DIR}/.bash_profile | grep bash_aliases &> /dev/null
if [ "$?" != 0 ]
  then
    printf "if [ -f .bash_aliases ]; then\n  . .bash_aliases\nfi" >> ${HOME_DIR}/.bash_profile
    if [ "$?" = 1 ] # could be readonline file system, core os for example
      then
        BASH_PROFILE_CONTENT=$(cat ${HOME_DIR}/.bash_profile)
        rm ${HOME_DIR}/.bash_profile
        printf "${BASH_PROFILE_CONTENT}\n\nif [ -f .bash_aliases ]; then\n  . ${HOME_DIR}/.bash_aliases\nfi" >> ${HOME_DIR}/.bash_profile
    fi
fi
